node:
  id: rpi_group_a
  role: receiver
  group: A

app:
  mode: SineWave
  update_period_s: 0.5

rf:
  center_frequency_hz: 2400000000
  sample_rate_hz: 1000000
  samples_per_frame: 4096
  rx_gain_db: 30
  sps: 2
  data_bits: 4096
  tone_frequency_hz: 10000

# Use either serial or uri. Serial is recommended because usb:X.Y.Z can change.
radios:
  - label: A1
    serial: "CHANGE_ME_PLUTO_SERIAL_A1"
    # uri: "usb:1.14.5"
  - label: A2
    serial: "CHANGE_ME_PLUTO_SERIAL_A2"

network:
  central_host: "192.168.1.100"
  central_port: 5555
